baseURL = "https://heunyam.github.io/"
languageCode = "ko-KR"
title = "Heunyam"
theme = "lightbi-hugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

[Params]
  commit = "https://github.com/heunyam/heunyam.github.io/tree/"
  author = "Heunyam"
  description = "In solitude, where we are least alone."
  github = "heunyam"


[Author]
  name = "Sejun Kim"
  email = "tpwns072@gmail.com"
  github = "heunyam"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 100
