name: Deploy to GitHub Pages

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Install Node.js
        uses: actions/setup-node@latest
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES: true

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@latest
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@latest